### ISSUE TITLE
The property Version inside the SkillResponse is not initialized

### ISSUE THREAD

**Issue by andreasassetti** [stoiveyp/Alexa.NET.FluentResponse#9]
Hi, I found a bug or I'm not handling correctly the Fluent class.

This is the simple test:
`return Fluent.Speak("OK").AndShouldEndSession(true).Response;`

In this case I have a SkillResponse object without any Version property filled, consequently during the serialization I have a null value serialization exception.

Regards
Andrea

**Comment by stoiveyp** [comment]
Hi @andreasassetti - absolutely right, so sorry. Pushing the fix through as we speak

**Comment by stoiveyp** [comment]
v1.1.3 now has the version set on the output response - sorry about that!

https://www.nuget.org/packages/Alexa.NET.FluentResponse/1.1.3

**Comment by andreasassetti** [comment]
@stoiveyp Thanks!
